### PR TITLE
Liking posts/threads.

### PR DESCRIPTION
**Pull request by lonnieezell**
This PR adds a "like" button to threads and posts. For performance reasons, all counts are de-normalized and kept on the threads, posts, and users tables. This seems pretty common from the 2-3 different forum databases I've seen, in order to minimize `count()` queries, since they can be slow. 

- Any likes on posts/threads will count as a like for that user
- Liking an already liked thread/post will toggle it, removing the like and decrementing the count for the thread/post and user.

To be able to keep the button as part of the theme, I refactored how the theming works by creating a `Theme` service so it can be called from more places than just the controller. 

This is one of the items needed to start working on the Trust system we discussed in #188 and can take the place of MyBB's reputation system as far as imports go. I decided to keep this simple and only track likes to hopefully help keep a more positive community. It's built in a way that it could be expanded later and use different reaction types in the future if needed. 

To be honest we could always launch the CI forums without the Trust system initially, since that might be a bigger build out, and add it later.

### CODE REVIEW

**Review by michalsn — COMMENTED** [review]
Problems I found:
* I can "like" my own post/thread
* We should use `post` type of request when we "like" post/thread since we change the application's state. 
* After "liking" the post/thread, the button is not aligned

**Comment by lonnieezell** [comment]
The styling I was aware of and forgot to mention as something I would worry about later. Not going to have much time over the next week or two I don't think.

Thanks for the reminder about post. Was having issues getting htmx and csrf to play nicely at first and forgot to go back and find a solution for that.

**Review by michalsn — APPROVED** [review]

**Comment by kenjis** [comment]
Most errors seem to be bugs that should be fixed.

```
 ------ --------------------------------------------- 
  Line   app/Common.php                               
 ------ --------------------------------------------- 
  61     Service method 'theme' returns mixed.        
         💡 Perhaps you forgot to add a return type?  
 ------ --------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   app/Concerns/HasAuthorsAndEditors.php (in context of class                
         App\Controllers\Moderation\ReportsController)                             
 ------ -------------------------------------------------------------------------- 
  62     Access to an undefined property                                           
         $this(App\Controllers\Moderation\ReportsController)::$author.             
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  83     Access to an undefined property                                           
         App\Controllers\Moderation\ReportsController::$author_id.                 
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   app/Concerns/HasAuthorsAndEditors.php (in context of class                
         App\Models\ModerationReportModel)                                         
 ------ -------------------------------------------------------------------------- 
  62     Access to an undefined property                                           
         $this(App\Models\ModerationReportModel)::$author.                         
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  83     Access to an undefined property                                           
         App\Models\ModerationReportModel::$author_id.                             
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   app/Concerns/HasAuthorsAndEditors.php (in context of class                
         App\Models\PostModel)                                                     
 ------ -------------------------------------------------------------------------- 
  62     Access to an undefined property $this(App\Models\PostModel)::$author.     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  83     Access to an undefined property App\Models\PostModel::$author_id.         
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   app/Concerns/HasAuthorsAndEditors.php (in context of class                
         App\Models\ThreadModel)                                                   
 ------ -------------------------------------------------------------------------- 
  62     Access to an undefined property                                           
         $this(App\Models\ThreadModel)::$author.                                   
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  83     Access to an undefined property App\Models\ThreadModel::$author_id.       
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   app/Concerns/HasReactions.php (in context of class                        
         App\Models\UserModel)                                                     
 ------ -------------------------------------------------------------------------- 
  12     Access to an undefined property App\Models\UserModel::$id.                
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  20     Access to an undefined property App\Models\UserModel::$id.                
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------- 

 ------ --------------------------------------------- 
  Line   app/Controllers/BaseController.php           
 ------ --------------------------------------------- 
  91     Service method 'theme' returns mixed.        
         💡 Perhaps you forgot to add a return type?  
 ------ --------------------------------------------- 

 ------ ------------------------------------------------------- 
  Line   app/Libraries/Theme.php                                
 ------ ------------------------------------------------------- 
  54     Method App\Libraries\Theme::renderer() should return   
         App\Libraries\View but returns CodeIgniter\View\View.  
 ------ ------------------------------------------------------- 

Error:  [ERROR] Found 13 errors         
```
https://github.com/lonnieezell/forum-example/actions/runs/7537200931/job/20515775675

**Comment by lonnieezell** [comment]
I agree they're simple, but they were unrelated to what I was working on at the time and I had other priorities for a few weeks. Those other priorities are taking longer than expected but I'm about 1/2 way through. Have tinkered a little more on this project but not much in that time.

**Pull request merged**
