### PR TITLE
Style the auth screens

### PR DESCRIPTION
**Pull request by lonnieezell**
- Updated Shield to `dev-develop` to take advantage of new namespace feature for auth routes
- Published views and restyled them
- Created new skeleton auth controllers in order to take advantage of our theme system.

### CODE REVIEW

**Comment by michalsn** [comment]
I get an error when loading the `login` or `register` page.

> Invalid file: "auth.php"

**Comment by lonnieezell** [comment]
Sounds like you need to do `composer update`. I changed Shield to `dev-develop` to take advantage of a new `namespaces` feature I just put in for `auth()->routes()`.

**Comment by michalsn** [comment]
Yes, you're right. This looks great!

**Comment by michalsn** [comment]
This PHPStan error is strange... I guess the `$users[$setting->user_id]` becomes a problem? Maybe I will check it tomorrow, but in the worst-case scenario, we can just suppress it.

**Review by michalsn — APPROVED** [review]

**Comment by lonnieezell** [comment]
Yeah, I wasn't sure about that one either. Couldn't figure out a quick fix. But cool. I was hoping you'd say we could fix it later :)

**Pull request merged**
