### PR TITLE
style: String config value to FQCN

### PR DESCRIPTION
**Pull request by neznaika0**
FQCN more friendly and gives hints of types

### CODE REVIEW

**Comment by michalsn** [comment]
While I agree when it comes to regular PHP files. I disagree about doing this for the view files.

**Comment by neznaika0** [comment]
The view files are not PHP? They also have syntax highlighting and annoying underscores of undefined parameters...

**Comment by michalsn** [comment]
I probably could have used different wording, however, I personally prefer not to use `use` in view files. 

But that's just me. I will adjust if necessary.

**Comment by neznaika0** [comment]
We can wait for the other participants. Everyone has different time zones

**Comment by datamweb** [comment]
@neznaika0 I thought a little about this PR. What I have noticed is that there has not been much desire to implement this method regarding Views.

I don't know what's the logic behind it, but views are not that important from the core team's point of view(maybe because the views can only be one HTML file). If you pay attention, we have [removed directory Views](https://github.com/lonnieezell/forum-example/blob/c7dd0b01eb48e3a24e6882c86218ed672337b089/phpstan.neon.dist#L13-L13) from the static analysis. This issue is also present in Shield and...

**Comment by neznaika0** [comment]
Hints are required by the developer and not by the analyzer. It is more convenient for me when there is auto-completion. Especially when the object has many fields and methods. Your desire, PR is canceled

**Comment by kenjis** [comment]
I prefer `::class` because I can autocomplete and jump to the definition.

**Comment by neznaika0** [comment]
But **Shield** contains always `config('Auth')`, for example

**Comment by kenjis** [comment]
It is because to allow override the Config by another module.
If you place `Config\Auth`, it will take precedence.
In most apps, you use `Config\Auth`, and `config(Config\Auth::class)` is no problem.

But if you don't use `Config\Auth`, and want to put it in another module like `Foo\Config\Auth`,
we need to use `config('Auth')`.

**Pull request closed without merging**
