### PR TITLE
fix: use `csrf` in form

### PR DESCRIPTION
**Pull request by datamweb**

### CODE REVIEW

**Comment by michalsn** [comment]
I believe `form_open()` handles this automatically.

**Comment by datamweb** [comment]
`form_open()`  handles this automatically when filter `'csrf'` below is active. There are currently `// 'csrf',`.

Am I missing something?
https://github.com/lonnieezell/forum-example/blob/eb3a12cc5208f812b993a8512efadc1c602e3ad7/app/Config/Filters.php#L36-L47

**Comment by michalsn** [comment]
If `csrf` filter is disabled, then even if we add `csrf_field()` to the form, it won't be verified. So, there is no point in adding this field manually.

**Comment by datamweb** [comment]
Ah, so we need to enable the csrf filter in app/Config/Filters.php.

**Comment by michalsn** [comment]
Yes, that's all we need - nothing more.

**Pull request closed without merging**
